Sprint_1: Вторая итерация проверки кода
ssavl/middle.messenger.praktikum.yandex pull request #2
Opened 2021-08-29 15:09 UTC by ssavl

Express / Handlebars / Parcel / Sass

2021-08-29 19:19 UTC, nickchamel requested changes
Привет еще раз. По коду все отлично! Хорошая работа. Но по заданию не все страницы присутствуют
![image](https://user-images.githubusercontent.com/28347933/131262749-ff3768ee-b9bf-404d-80ba-c84d055b5e1f.png)
ты сделал ту, которую было делать не обязательно сейчас)
Как минимум для того, чтобы работа была принята нужны еще страницы:
- профиль
- логин
- регистрация
- 404
- 500
Давай доделаем их и двинемся дальше

2021-08-29 19:19 UTC, nickchamel commented on src/helpers/hello.js
> +
если parcel/hbs позволяет здесь использовать es6 импорты, то лучше использовать их, чтобы код выглядит в одном стиле

2021-08-29 19:19 UTC, nickchamel commented on src/index.hbs
> +
было бы неплохо убрать лишние переводы строк, чтобы все выглядело аккуратно (в других файлах тоже присутствует этот момент)

2021-08-29 19:19 UTC, nickchamel commented on src/sass/index.sass
> +  background: blue
вообще лучше использовать переменные для основных единиц (цвета, размеры шрифтов и тд)
Но если у тебя будет только синий, то тут конечно другой разговор)

2021-08-29 19:19 UTC, nickchamel commented on package.json
> +    "start": "concurrently \"npm run client\" \"npm run server\"",
так ты запустишь одновременно и парсел watch-сборку и экспресс-сервер. До этого у тебя все основные команды присутсвуют

2021-08-30 06:26 UTC, ssavl commented on src/helpers/hello.js
> +
Тут есть нюансы с импортами, парсел плохо понимает синтаксис es6 нам куратор сказал на отдельном созвоне конкретно так прописывать их 🤷🏼‍♂️

2021-08-30 06:26 UTC, ssavl commented on src/index.hbs
> +
Спасибо! Сделаю)

2021-08-30 06:27 UTC, ssavl commented on src/sass/index.sass
> +  background: blue
ОК, да думал что так сделать нужно, я тогда про дизайн еще подумаю на сл спринте, точно определюсь с цветами и на новой итерации вынесу цвета в отдельные переменные 👌🏻

2021-08-30 06:30 UTC, ssavl commented on package.json
> +    "start": "concurrently \"npm run client\" \"npm run server\"",
Никит, прости, немного не понял поинт. Мне исправить команду start? в ней что-то не то? Да, я понимаю что используя concurrently я запускаю и сборку парсела и сервер одновременно

2021-08-30 07:23 UTC, nickchamel commented on package.json
> +    "start": "concurrently \"npm run client\" \"npm run server\"",
Можешь не исправлять, главное что понимаешь) я просто имел ввиду что незачем запускать оба этих процесса одновременно)

2021-08-30 08:17 UTC, nickchamel commented
Привет. Отлично. Только надо было на них ссылки сделать, чтобы парсель их сбилдил и были переходы на них. Щас не сильно критично, так как смотреть там особо нечего, но на будущее учти, пожалуйста.
Еще совет - разбить чуть больше на модульную структуру, в частности sass - чтобы стили каждой страницы/компонента лежали в своей папке, например pages/login. там лежит шаблон логина, стили логина, js логина.

2021-09-01 13:27 UTC, ssavl commented on src/helpers/hello.js
> +
@nickchamel Никит, а ты смержишь ветку с main?

2021-09-01 13:27 UTC, ssavl commented on src/helpers/hello.js
> +
или это мне нужно сделать ?

2021-09-01 15:37 UTC, nickchamel commented on src/helpers/hello.js
> +
@ssavl привет. да, ты сам можешь мерджить, когда приняли работу.

2021-09-14 08:25 UTC, merged