Первая итерация проверки второго спринта: Добавил TS
ssavl/middle.messenger.praktikum.yandex pull request #3
Opened 2021-09-15 11:01 UTC by ssavl

Первая итерация проверки второго спринта: Добавил: 
- TS, 
- Eslint, 
- Stylelint, 
- Разбил на компоненты проект
- Сборка с помощью Parcel
- Своя реализация fetch

2021-09-15 15:32 UTC, bhoodream requested changes
Отличная работа! Есть некоторые комментарии от меня по коду, было бы хорошо, если бы ты поработал над ними. Также есть серьезные недоработки по заданиям второго спринта:
- [ ] не нашел страниц с формами, где должно быть:
    - [ ] сбор данных и вывод в консоль (пункт 5)
    - [ ] валидация (пункт 6)
- [ ] не нашел страниц (пункт 7)
- [ ] не заметил шаблона MVC (пункт 9)
- [ ] почему то компоненты/константы/хелперы и тд находятся в корне проекта, хотя должны быть в папке `/src`
- [ ] eslint падает с ошибкой
- [ ] не добавлен stylelint

2021-09-15 15:32 UTC, bhoodream commented on .eslintrc.json
> +//    "extends": "airbnb-base/legacy",
Комменты надо подчищать, потому что они засоряют кодовую базу

2021-09-15 15:32 UTC, bhoodream commented on components/blocks/Button/index.ts
> +    return `<a class='${className}'
Очень интересная кнопка, которая на самом деле может оказаться ссылкой. Думаю это будет совсем неожиданно для пользователей этого блока.

2021-09-15 15:32 UTC, bhoodream commented on components/blocks/Input/Input.sass
> +  &-chat
Собирая селектор с помощью амперсанда (&) ты можешь в будущем столкнуться с проблемами поиска некоторых селекторов по проекту. Также такой способ получения селекторов создает дополнительную вложенность, что вредит читабельности.

Амперсанд хорош при создании селекторов по типу потомков, псевдо(классов/элементов) и модификаторов.

Менять ничего не требуется, просто небольшая ремарка.

2021-09-15 15:32 UTC, bhoodream commented on components/blocks/ChatItem/index.ts
> +    return `<div class="${className}__item">
`ChatItem` наверное семантически будет уместнее представлять в виде `<li>` элемента, который вставляется в список, который будет `<ul>` элементом.

2021-09-15 15:32 UTC, bhoodream commented on helpers/api-call.ts
> +    return queryString.join('').slice(0, -1)
Здесь в свою очередь правильнее было сделать `.join('&')`, чем лепить амперсанд (&)  в конце каждой пары `ключ=значение` и потом отрезать его у результата...

2021-09-15 15:32 UTC, bhoodream commented on helpers/api-call.ts
> +    let queryString = ['?', ]
Думаю проще было бы подставить `?` при возврате результата, чем усложнять изначальный массив. Изначальный массив вообще должен быть пустым `[]`

2021-09-15 15:32 UTC, bhoodream commented on helpers/api-call.ts
> +            const GetOrShit = (url, method) => {
Название функций и переменных это святое :) Если ты собираешься работать в команде, то лучше относиться к написанию кода с уважением

2021-09-15 15:32 UTC, bhoodream commented on helpers/api-call.ts
> +            if ( METHODS.GET || !data) {
Ты здесь просто проверяешь константу? `METHODS.GET`

2021-09-15 15:32 UTC, bhoodream commented on index.js
> +var qwe = 'Savelii'
Мусор лучше подчищать в проекте

2021-09-15 15:32 UTC, bhoodream commented on modules/Block/index.ts
> +        // Этот небезопасный метод для упрощения логики
Непонятные комментарии только засоряют код. Думаю здесь бы гораздо уместнее была тудушка, типа `@TODO: решить вопрос безопасности рендера`

2021-09-15 15:32 UTC, bhoodream commented on modules/EventBus/index.ts
> +        if (this.listeners[event] === null || !this.listeners[event]) {
`null` тоже попадет под такую проверку `!this.listeners[event]`

2021-09-15 15:32 UTC, bhoodream commented on package.json
> +    "client": "parcel src/index.hbs",
обычно команду для разработки называют `dev`

2021-09-15 15:32 UTC, bhoodream commented on package.json
> +    "start": "concurrently \"npm run client\" \"npm run server\" \"eslint \"./\"\"",
Вместо команды `client` здесь должны по порядку быть запущены команды `build` и `server`. Команда `eslint` тут вообще не нужна

2021-09-15 15:32 UTC, bhoodream commented on src/layouts/main.hbs
> +    <link rel="stylesheet" type="text/css" href="../components/blocks/Button/Button.sass">
Кажется было бы уместнее подключить стили этих блоков в общем `index.sass` файле

2021-09-15 19:02 UTC, ssavl commented on src/layouts/main.hbs
> +    <link rel="stylesheet" type="text/css" href="../components/blocks/Button/Button.sass">
@bhoodream я просто не совсем понял как подключить кучу sass файлов, которые я до этого декомпозировал в разных компонентах - до этого было тупо один index.sass решил разбить стили для каждого элемента UI

2021-09-15 19:03 UTC, ssavl commented on package.json
> +    "start": "concurrently \"npm run client\" \"npm run server\" \"eslint \"./\"\"",
@bhoodream а как мне во время работы надо проектом сделать так чтобы линртер проверял проект? я кроме того чтобы постоянно дергать eslint ./ ничего не придумал и запихнул ее тупо в npm run start

2021-09-15 19:03 UTC, ssavl commented on package.json
> +    "client": "parcel src/index.hbs",
Согласен! пофикшу

2021-09-15 19:04 UTC, ssavl commented on modules/EventBus/index.ts
> +        if (this.listeners[event] === null || !this.listeners[event]) {
Топ, исправлю

2021-09-15 19:04 UTC, ssavl commented on helpers/api-call.ts
> +            if ( METHODS.GET || !data) {
тут я проверяю что метод === GET

из объекта константы достаю это

2021-09-15 19:06 UTC, ssavl commented on helpers/api-call.ts
> +    return queryString.join('').slice(0, -1)
Это просто афигеть как круто, как я сам не догадался)))

2021-09-15 19:06 UTC, ssavl commented on components/blocks/ChatItem/index.ts
> +    return `<div class="${className}__item">
Постараюсь, но пока сложно, очень хочу успеть все сделать до пятницы

2021-09-15 19:07 UTC, ssavl commented on components/blocks/Button/index.ts
> +    return `<a class='${className}'
@bhoodream Вадим поясни пожалуйста, странная логика?

2021-09-16 05:23 UTC, bhoodream commented on components/blocks/Button/index.ts
> +    return `<a class='${className}'
Да, щас поясню. Я имел ввиду, что когда ты используешь компонент с названием `Button` ты ожидаешь кнопку на выходе, то есть `button`. Она может выглядеть как что угодно, в том числе и как ссылка, но все таки семантически должна оставаться кнопкой. В твоем же случае мы хотим кнопку, а можем получить ссылку, элемент `a`.

2021-09-16 05:26 UTC, bhoodream commented on package.json
> +    "start": "concurrently \"npm run client\" \"npm run server\" \"eslint \"./\"\"",
:) Обычно линтеры настраиваются в том редакторе/иде в котором работаешь. Если ты например работаешь в vscode, то для этого используются плагины, например такие https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint и https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint

2021-09-16 05:37 UTC, bhoodream commented on src/layouts/main.hbs
> +    <link rel="stylesheet" type="text/css" href="../components/blocks/Button/Button.sass">
В рамках модульного подхода стили обычно подключаются в скрипте, прямо так:
```
import './Button.sass'
```
Бандлер (parcel/webpack) уже сам их подхватывает и собирает в виде отдельных бандлов/чанков. Попробуй покопай в этом направлении.

2021-09-16 05:43 UTC, bhoodream commented on helpers/api-call.ts
> +    return queryString.join('').slice(0, -1)
Вроде писал, но комент куда-то потерялся... напишу еще раз. Вопрос (`?`) наверное лучше было бы отдавать в конце, типа так `?${queryString.join('&')}`. Тогда изначальный `queryString` массив можно инициализировать пустым `[]`, ну и назвать его что то типа `params`.

2021-09-16 05:45 UTC, bhoodream commented on helpers/api-call.ts
> +            if ( METHODS.GET || !data) {
Да, но у тебя запись `if ( METHODS.GET || !data)` , то есть это выражение у тебя всегда будет `true`, чтобы бы было так как ты задумывал, надо запись сделать такую `if ( method === METHODS.GET || !data)` :)

2021-09-16 18:18 UTC, ssavl commented
> Отличная работа! Есть некоторые комментарии от меня по коду, было бы хорошо, если бы ты поработал над ними. Также есть серьезные недоработки по заданиям второго спринта:
> 
> * [ ]  не нашел страниц с формами, где должно быть:
>   
>   * [ ]  сбор данных и вывод в консоль (пункт 5)
>   * [ ]  валидация (пункт 6)
> * [ ]  не нашел страниц (пункт 7)
> * [ ]  не заметил шаблона MVC (пункт 9)
> * [ ]  почему то компоненты/константы/хелперы и тд находятся в корне проекта, хотя должны быть в папке `/src`
> * [ ]  нет команды линтинга:
>   
>   * [ ]  линтинг скриптов
>   * [ ]  линтинг стилей

@bhoodream Не понял про команды линтинга скриптов и стилей? подключил ведь eslint и stylelint (package.json) и конфиг в корне + запускается скрипт при дев-запуске сборщика

2021-09-17 06:29 UTC, bhoodream commented
Насчет линтига можешь не заморачиваться, обычно заводят команды типа `lint:scripts/lint:styles` для их запуска на хуках. А чтобы линтинг происходил в редакторе подключают плагины.

2021-09-18 01:55 UTC, ssavl commented on .eslintrc.json
> +//    "extends": "airbnb-base/legacy",
@bhoodream Вадим привет, закомитил изменения, реализовал чего до этого не было, к примеру формы и валидации, посмотри пожалуйста

2021-09-20 14:10 UTC, bhoodream requested changes
Нужно обязательно сделать:
- [ ] работающая валидация на формах. Сейчас есть только какая-то недоделка, которая даже не используется нигде... По крайней мере я не нашел место, где бы код загрузки и валидации формы отработал. Смотрел на странице авторизации/регистрации;
- [ ] при отправке формы страница перезагружается и как и прежде ничего не логируется. Необходимо сделать чтобы форма не перезагружалась и в консоль выводились все введенные данные в форму;
- [ ] нетлифай 404 - проверяю по ссылке https://lucid-leakey-476aa8.netlify.app . Нужно добиться того, чтобы проект был корректно развернут на netlify

2021-09-20 14:10 UTC, bhoodream commented on index.hbs
> +<div id="app">
Этот шаблон также надо внести внутрь `/src` так как он является исходником.

2021-09-20 14:10 UTC, bhoodream commented on src/components/blocks/Button/Button.hbs
> +<button class="{{class}}">{{text}}</button>
у кнопки должен быть `type` обязательно, иначе браузер может неверно интерпретировать ее назначение, что приведет к некорректному поведению. Обычно используют `type="button"`, для загрузки форм используется `submit`, есть еще тип `reset`, но я им не пользовался ни разу :)

2021-09-20 14:10 UTC, bhoodream commented on src/components/blocks/ChatItem/ChatItem.ts
> +    componentDidUpdate(oldProps: any, newProps: any): boolean {
`Block`, класс от которого ты наследуешь, по-умолчанию возвращает `true`. По идее нет необходимости переопределять этот метод тем же поведением.

2021-09-20 14:10 UTC, bhoodream commented on src/components/blocks/Form/Form.sass
> +.Form
Какой-то пустой селектор у тебя получился, видать что-то хотел сделать, но забыл. Такое лучше убирать.

2021-09-20 14:10 UTC, bhoodream commented on src/components/blocks/Form/Form.ts
> +        console.log('Input Value', formElement[0].value);
Нужно залогировать все данные формы, ты же выведешь только данные первого инпута.

2021-09-20 14:10 UTC, bhoodream commented on src/components/blocks/Form/Form.ts
> +        if (String(formElement[0].value).match(this.props.re)) {
валидация в таком случае тоже будет проверять только первый инпут. Непонятно мне что за недоделки в этом файле и где они вообще используются... Подскажи, где именно используется код из этого файла? Я так и не нашел этого места

2021-09-20 14:10 UTC, bhoodream commented on src/helpers/api-call.ts
> +            if ( METHODS.GET || !data) {
Ты так и продолжаешь проверять константу? Мне что-то подсказывает и почему то 100% в этом уверен, что здесь надо сделать проверку `method === METHODS.GET` :) Я тебе вроде даже уже об этом писал...

2021-09-30 11:48 UTC, ssavl commented on src/components/blocks/Form/Form.sass
> +.Form
Добавил стили

2021-09-30 11:48 UTC, ssavl commented on src/components/blocks/ChatItem/ChatItem.ts
> +    componentDidUpdate(oldProps: any, newProps: any): boolean {
ок

2021-09-30 11:49 UTC, ssavl commented on src/components/blocks/Button/Button.hbs
> +<button class="{{class}}">{{text}}</button>
Изменил - добавил type в Button.hbs

2021-09-30 11:49 UTC, ssavl commented on index.hbs
> +<div id="app">
вынес все рабочие файлы в src
в корне только конфиги и server.js

2021-09-30 11:51 UTC, ssavl commented on src/components/blocks/Form/Form.ts
> +        console.log('Input Value', formElement[0].value);
при нажатии value импута выводится в консоль, при Blur происходит проверка на специальные символы и если они есть -- выводится error в div под формой

2021-09-30 11:54 UTC, ssavl commented on src/components/blocks/Form/Form.ts
> +        if (String(formElement[0].value).match(this.props.re)) {
У меня две формы одна FormLogin, вторая Form 

1. Form выводится в импуте где нужно вводить сообщение в Home.hbs там один импут и одна проверка в нем (если в импуте есть специальные символы то выводится сообщение в div )
2. FormLogin выводится на странице логина в Login.hbs -- там проверяется и валидируется только импут логина так как пароль по логике бессмысленно валидировать он как раз должен состоять из специальных символов  в том числе

2021-09-30 11:54 UTC, ssavl commented on src/helpers/api-call.ts
> +            if ( METHODS.GET || !data) {
Исправил

2021-10-01 05:21 UTC, bhoodream requested changes
На данный момент твой проект вообще не работоспособен, нужно поправить. Проблемы:
- [ ] ссылки в шапке щас ведут на http://localhost:1234/components/pages/Home/Home.js , это что то очень странное... Ссылки должны вести туда, куда надо. Чат в раздел чата, профиль в раздел профиля и так далее.
- [ ] команда `client` должна называться командой `dev`, потому что в ней запускается дев режим с помощью парселя
- [ ] я уже писал и напишу еще раз, команда `start` должна билдить проект (команда `build`) и запускать сервер (команда `server`). Сейчас она у тебя запускает проект в дев режиме на паселе на 1234 порту и сервер на 3000 порту, который раздает старый дист. Это также что-то очень странное... И кстати, никаких параллельных запусков с помощью `concurrently` здесь не надо.

2021-10-01 05:25 UTC, bhoodream commented on src/components/blocks/FormLogin/FormLogin.ts
> +        console.log(formElement[0].value);
Ты так и продолжаешь логировать результат только первого инпута...

Код this.element.getElementsByTagName('input') возмет все инпуты со страницы, это будет набор html элементов. С помощью formElement[0] ты берешь только первый элемент, а задание, вывести в консоль все значения.

Немного удручает, что мне приходится по несколько раз тебе говорить одно и тоже... Я уже тебе писал все что сейчас сказал выше...

2021-10-01 05:28 UTC, bhoodream commented on src/components/blocks/FormLogin/FormLogin.ts
> +        if (formElement[0].value.match(this.props.re)) {
Ты опять же берешь только первый элемент `formElement[0]` (объяснение почему есть выше). И проверив только первый элемент ты ставишь ошибки и в логин и пароль... Это что за магия? Откуда ты знаешь что проблемы с ними? Ты же просто взял первый инпут со страницы, им может быть вообще любой инпут, который первым попадется на странице...

2021-10-01 08:25 UTC, ssavl commented on src/components/blocks/FormLogin/FormLogin.ts
> +        console.log(formElement[0].value);
@bhoodream Вадим, мне очень нужно перейти дальше, к следующему модулю, я правильно понимаю что чтобы пройти мне нужно просто исправить замечания написанные вышел ?

1. Ссылки должны вести в правильные места (чат в /chat итд)
2. Исправить команды client на dev И так далее (все что в замечаниии)
3. Исправить команду start (все что в замечании)

у меня просто очень горят дедлайны, хотелось бы получить апрув и дальше двинуться

2021-10-01 08:44 UTC, ssavl commented on src/components/blocks/FormLogin/FormLogin.ts
> +        console.log(formElement[0].value);
@bhoodream Вадим, у меня второй вопрос на `npm run start` я должен сбилдить проект используя (`parcel build index.html`) и запустить сервер используя (`node server.js`) вопрос: Как мне прописать это в npm run start **НЕ ИСПОЛЬЗУЯ** `concurrently `?  Ведь эта команда для этого и существует чтобы засунуть в одну cli команду два действия ?

2021-10-01 08:54 UTC, ssavl commented on src/components/blocks/FormLogin/FormLogin.ts
> +        if (formElement[0].value.match(this.props.re)) {
@bhoodream  Вадим, можно я погружусь и сделаю импуты чуть позже когда буду в третьем спринте курса настраивать api и роутинг, на сколько я понимаю сейчас формальные условия выполнены, проверка по регулярке проходит, cсообщение выводится, страницы реализованы, проект на стенде висит 

зачтите пожалуйста

2021-10-01 09:13 UTC, bhoodream commented on src/components/blocks/FormLogin/FormLogin.ts
> +        console.log(formElement[0].value);
`npm run build && npm run server`

2021-10-01 15:28 UTC, ssavl commented on src/components/blocks/FormLogin/FormLogin.ts
> +        console.log(formElement[0].value);
@bhoodream Все сделал! Пожалуйста проверь!

2021-10-01 16:10 UTC, bhoodream approved these changes
Годится!

2021-10-04 06:15 UTC, merged

2021-10-13 11:28 UTC, ua9msn requested changes
Очень моно чего имеет тип `any`  Это не оч хорошо

2021-10-13 11:28 UTC, ua9msn commented on package.json
>      "sass": "^1.38.1"
sass parcel и eslint должны быть в devDependency

2021-10-13 11:28 UTC, ua9msn commented on src/modules/Compile/index.ts
> +    const fragment = document.createElement('template')
`props` указан как `any` но ниже вы явно ожидаете объект

2021-10-13 11:28 UTC, ua9msn commented on src/modules/Compile/index.ts
> +}
А зачем снчала делать заглушки а потом их заменять?

2021-10-13 11:28 UTC, ua9msn commented on src/modules/EventBus/index.ts
> +        }
Это выглядит очень странно. Во первых, у вас создаются события только при подписке на них. Но в общем случае события могут случаться даже если их никто не слушает.
Во вторых `this.listeners` у вас определен в конструткторе а вы проверяете его отсутствие. Что на самом деле вы хотите проверять?

2021-10-13 11:28 UTC, ua9msn commented on src/helpers/api-call.ts
> +        throw new Error ('data is not a object')
`data` должен иметь тип `unknown` иначе  `if` не есть `typeguard`

2021-10-13 11:28 UTC, ua9msn commented on src/helpers/api-call.ts
> +}
Вы же добавите типы в класс `HTTPTransport`?