Добавил dockerfile, сборку проекта через webpack, pre-commit
ssavl/middle.messenger.praktikum.yandex pull request #5
Opened 2021-10-24 12:19 UTC by ssavl

Четвертый и последний пулу реквест первого модуля: добавил webpack вместо parcel, сборка проекта в докере, прекомиты

2021-10-24 19:59 UTC, khitrind requested changes
Спасибо за вашу работу, все выглядит отлично, но к сожалению я не увидел ссылку на heroku, добавьте ее пожалуйста в readme (3 пункт ТЗ):

> 3. Разместите в Heroku проект с Docker-сборкой. Ссылка на документацию Heroku о деплое проекта с Docker.

2021-10-24 19:59 UTC, khitrind commented on .dockerignore
> +dist
[EOF](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)
https://eslint.org/docs/rules/eol-last

2021-10-24 19:59 UTC, khitrind commented on webpack.config.js
> +};
EOF

2021-10-24 19:59 UTC, khitrind commented on webpack.config.js
> +    mode: 'development',
Все выглядит отлично, но лучше разделить сборку по конфигам, на production и development https://webpack.js.org/guides/production/

2021-10-25 07:14 UTC, ssavl commented on .dockerignore
> +dist
@DmitryKhitrin спасибо большое за ревью, сейчас прикреплю ссылку на хироку, подскажите пожалуйста, что мне нужно в этом комментарии добавить в докеригнор? Я не очень понял по поводу EOF, мне нужно `;` поставить в конце?

2021-10-25 07:15 UTC, ssavl commented on webpack.config.js
> +};
@DmitryKhitrin я забыл где-то `;` поставить?

2021-10-25 07:16 UTC, ssavl commented on webpack.config.js
> +    mode: 'development',
@DmitryKhitrin спасибо! отличный совет! не думал об этом

2021-10-26 22:42 UTC, ssavl commented on .dockerignore
> +dist
Сборку на хероку добавил

2021-10-26 22:43 UTC, ssavl commented on .dockerignore
> +dist
https://supermessenger.herokuapp.com/  (в ридми есть)

2021-10-28 06:41 UTC, ssavl commented on .dockerignore
> +dist
@DmitryKhitrin Очень спешу, сегодня у меня последний день для сдачи

2021-10-28 08:41 UTC, khitrind approved these changes
Удачи в следующем спринте, дальше только интереснее)

2021-11-05 09:01 UTC, merged